require 'plumnailer/chooser'
require 'plumnailer/doc_parser'
require 'plumnailer/doc'
require 'plumnailer/fetcher'
require 'plumnailer/img_hostname_filter'
require 'plumnailer/img_parser'
require 'plumnailer/scorer'
require 'plumnailer/web_image'

require 'plumnailer/caching_fetcher'
