require 'plumnailer/chooser'
require 'plumnailer/doc_parser'
require 'plumnailer/doc'
require 'plumnailer/fetcher'
require 'plumnailer/img_comparator'
require 'plumnailer/img_parser'
require 'plumnailer/img_url_filter'
require 'plumnailer/web_image'

require 'plumnailer/caching_fetcher'
